name: eventtide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-214.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_calendar: ^25.2.7
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  card_swiper: ^3.0.1
  flutter_facebook_auth: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:  
  assets:    #Include images
    - assets/Roskilde_logo.png
  uses-material-design: true #Include icons
