name: eventtide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-214.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  card_swiper: ^3.0.1
  sign_in_button: ^3.0.0 #Google SignIn Knap
  intl: ^0.19.0
  firebase_storage: ^12.0.1
  image_picker: ^1.1.2
  calendar_view: ^1.2.0
  syncfusion_flutter_calendar: ^21.2.3
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:  
  assets:    #Include images
    - assets/Roskilde_logo.png
    - assets/RF23_Map.png
  uses-material-design: true #Include icons
